name: rent_split_malaysia
description: A Flutter app for splitting rent and TNB electricity bills fairly among Malaysian tenants
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3  # For desktop support
  path: ^1.8.3
  
  # Utilities
  uuid: ^4.4.2
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  
  # File handling for property photos
  path_provider: ^2.1.3

  # Export functionality
  share_plus: ^7.2.2
  pdf: ^3.10.7
  printing: ^5.12.0

  # Malaysian specific
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # App Icon
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Fonts for better Malaysian text display
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700

# Additional configuration for Malaysian market
flutter_intl:
  enabled: true
  main_locale: en
  supported_locales:
    - en
    - ms  # Bahasa Malaysia support